#Sources
:sources:
  Product:
    :poll_interval: 300

:development:
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292
  :push_server: https://someappname@rhoconnectpush.herokuapp.com/
  :api_token: my-rhoconnect-token
:test:
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292
  :push_server: https://someappname@rhoconnectpush.herokuapp.com/
  :api_token: my-rhoconnect-token
:production:
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292
  :push_server: https://someappname@rhoconnectpush.herokuapp.com/
